---
application:
  name: "jschess"
  project: "jschess"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "jschess"
  version: "4.4"
routers:
- name: "main-jschess"
  routes:
  - application_name: "jschess"
    paths:
    - "/*"
